swagger: "2.0"
info:
    description: >-
        Specify possible API endpoints needed for phase two of Argent Bank project
        (get transactions
    version: 1.0.0
    title: Argent Bank Documentation
    termsOfService: http://swagger.io/terms/
host: localhost:3000
basePath: /api/v1
tags:
    - name: User Transactions Module
      description: accounts transactions operations
schemes:
    - http
paths:
    /user/transactions/date:
        get:
            security:
                - Bearer: []
            tags:
                - User Transactions Module
            summary: Get User Transactions
            description: "API for Transactions sort by date, to allow user to get them monthly "
            parameters:
                - in: header
                  name: Authorization
                  description: attach Bearer JWT token
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: transactions retrieved successfully
                    schema:
                        $ref: "#/definitions/Transactions"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error
    /user/transaction/id:
        put:
            security:
                - Bearer: []
            tags:
                - User Transaction Module
            summary: Edit user transaction
            description: API for editing user transactions
            produces:
                - application/json
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: body
                  name: body
                  description: Edit user transaction category and notes item
                  required: true
                  schema:
                      $ref: "#/definitions/Transaction"
            responses:
                "200":
                    description: transaction edited successfully
                "400":
                    description: Invalid Fields
                "500":
                    description: Invalid Server Error
securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header
definitions:
    Transactions:
        type: object
        properties:
            id:
                type: integer
                description: transaction id
            date:
                type: string
                description: transaction date
            description:
                type: string
                description: transaction description
            amount:
                type: number
                description: transaction amount
            balance:
                type: number
                description: account balance
            transaction type:
                type: string
                description: transaction type
    Transaction:
        type: object
        properties:
            id:
                type: number
                description: transaction id
            date:
                type: string
                description: transaction date
            description:
                type: string
                description: transaction description
            amount:
                type: number
                description: transaction amount
            balance:
                type: number
                description: account balance
            transaction type:
                type: string
                description: transaction type
            category:
                type: string
                description: category type
            notes:
                type: string
                description: transaction notes
